// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_o7mQC-KbyxK6iFZ28IrsvnGpzLw1L-0',
    appId: '1:36244654330:web:8cb694a5a34eb78147e143',
    messagingSenderId: '36244654330',
    projectId: 'unimark-ffb10',
    authDomain: 'unimark-ffb10.firebaseapp.com',
    storageBucket: 'unimark-ffb10.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_o7mQC-KbyxK6iFZ28IrsvnGpzLw1L-0',
    appId: '1:36244654330:android:8cb694a5a34eb78147e143',
    messagingSenderId: '36244654330',
    projectId: 'unimark-ffb10',
    storageBucket: 'unimark-ffb10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_o7mQC-KbyxK6iFZ28IrsvnGpzLw1L-0',
    appId: '1:36244654330:ios:8cb694a5a34eb78147e143',
    messagingSenderId: '36244654330',
    projectId: 'unimark-ffb10',
    storageBucket: 'unimark-ffb10.firebasestorage.app',
    iosBundleId: 'com.unimark.attendance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_o7mQC-KbyxK6iFZ28IrsvnGpzLw1L-0',
    appId: '1:36244654330:ios:8cb694a5a34eb78147e143',
    messagingSenderId: '36244654330',
    projectId: 'unimark-ffb10',
    storageBucket: 'unimark-ffb10.firebasestorage.app',
    iosBundleId: 'com.unimark.attendance',
  );
}
